### ISSUE TITLE
\s[8] might be a typo for \s{8} ?

### ISSUE THREAD

**Issue by sebbASF** [apache/whimsy#107]
https://github.com/apache/whimsy/blob/5b23bfc97e3c3b05ea03cfe76366a536ce68fc57/lib/whimsy/asf/agenda/discussion.rb#L15

@rubys  It looks like the [8] might be a typo for {8}?

**Comment by sebbASF** [comment]
If it is really intended to match just '8', then the surrounding [] should be dropped

**Comment by rubys** [comment]
It is meant to match ```8```, the square brackets are unnecessary here.    Presumably it was copied and adapted from another place where more than one character was matched.
