### ISSUE TITLE
Agenda new action responding with 500 status

### ISSUE THREAD

**Issue by royfielding** [apache/whimsy#109]
This seems to be an odd one, perhaps caused by a recent change to committee-info or the process for reading that file, or maybe something in the December minutes.

I am getting a 500 error from whimsy agenda when trying to generate a new agenda file. That's all I get -- nothing else in the response or logs. I have not seen any errors on other agenda views, and the last meeting agenda seems to be fine.

Server time of an attempt was 2020-12-19T00:51:49.

I checked the changes to committee-info.txt after the meeting (removing Metron and Sentry) and they seem fine. I've also checked the code and everything else I can think of. Next step would be to instrument the view action so that it can tell me where it is failing, but I have no time.

**Comment by rubys** [comment]
See:

* https://github.com/rails/rails/issues/40884
* https://lists.apache.org/thread.html/r125240a4bbf350bece8baf8bb78567bce21f3cbd1c128bf408787c12%40%3Cdev.whimsical.apache.org%3E

**Comment by royfielding** [comment]
confirmed fix, thanks Sam,
