### ISSUE TITLE
update titles in agenda for new bylaws

### ISSUE THREAD

**Issue by royfielding** [apache/whimsy#114]
So, with the change to Board Chair, I am getting a 404 on the link to

   https://whimsy.apache.org/board/minutes/Board_Chair

as opposed to some copy or redirect to

  https://whimsy.apache.org/board/minutes/Chairman

I am not sure what is the best way to update that so that we preserve the trail back from agenda.

Likewise, I assume the same is true for Vice Chair. Haven't tested.

**Comment by sebbASF** [comment]
The minutes are parsed by tools/collate_minutes.rb
Project name changes are done here:
https://github.com/apache/whimsy/blob/a876d2f90c9263c3cf781212bc135abd2bce790d/tools/collate_minutes.rb#L178

Probably what needs to be done is to convert Chairman to Board Chair when parsing, so all the relevant data is in a single file, and then use the .htaccess file to redirect Chairman to Board Chair.

Make sense?

**Comment by sebbASF** [comment]
Committed 0722e78 which I hope fixes it.
Turns out the officer report name changes are done elsewhere

**Comment by royfielding** [comment]
Yes, that fixes it, thanks! But it looks like a duplicate redirect was added to .htaccess

**Comment by sebbASF** [comment]
Oops -- good catch, fixed the dupe.
