### ISSUE TITLE
Subscription to security@jackrabbit.apache.org cannot be managed via https://whimsy.apache.org/committers/subscribe

### ISSUE THREAD

**Issue by kwin** [apache/whimsy#137]
Although the subscription is visible in https://whimsy.apache.org/roster/committer/kwin I cannot manage the subscription to this particular list in https://whimsy.apache.org/committers/subscribe.
It is not listed in the drop-down in the Unsubscribe section.

**Comment by sebbASF** [comment]
By design, it's not possible to auto-subscribe to a security@ list, but it should be possible to unsubscribe.

The code currently does not allow for it, but you can always unsubscribe manually.

**Comment by kwin** [comment]
@sebbASF Thanks a lot for the answer and the clarification in the UI now!
