### ISSUE TITLE
Unable to see mailing lists I'm subscribed to

### ISSUE THREAD

**Issue by stillalex** [apache/whimsy#36]
As per this info [0], I should be able to see what lists I'm subscribed to, but this is empty in my case. 

For ex. I was already part of committers@ but this was not listed. And the lists I subscribed to today also don't appear (project specific lists).

[0] https://www.apache.org/foundation/mailinglists.html#subscribing

**Comment by rubys** [comment]
Subscription lists are update every six hours.  Try again in a few hours?

**Comment by stillalex** [comment]
sure, not a problem. will report back tomorrow :)

**Comment by stillalex** [comment]
checked again, looks a lot better now! feel free to close this issue :)
you could add a disclaimer to the subscriptions page about this update policy to set the expectations right.
