### ISSUE TITLE
Simplify instructions for posting board reports in reminder emails

### ISSUE THREAD

**Issue by psteitz** [apache/whimsy#41]
The initial and "now due" reminder emails sent to projects expected to report should drop the instruction to send plain text mail to board@.  Instructions on manual svn commit should also be dropped.  Instructions should just tell chairs to post to Whimsy.

**Comment by ShaneCurcuru** [comment]
These emails are in here if you want to wordsmith directly:

https://github.com/apache/whimsy/tree/master/www/board/agenda/data

**Comment by psteitz** [comment]
PR is [here](https://github.com/apache/whimsy/pull/43)

**Comment by sebbASF** [comment]
Appears to have been completed.
Please raise a WHIMSY JIRA if not (rather than a GitHub issue).
