### ISSUE TITLE
layout change request

### ISSUE THREAD

**Issue by gstein** [apache/whimsy#6]
With the recent change to move notes/comments to the right-hand column, that information now gets obscured by the perma-dropdown-Info panel. My overall suggestion is to get rid of the "Info" dropdown. Specific ideas below.

The currently layout appears to assume landscape mode. Given that, then you have lots of menubar space. I would suggest moving the "Links" up next to the project name. For example:

Any23 (Roster, Prior Reports, Statistics)

On the right column, there is a sometimes-yellow-bubble indicating something like "missing in February". I would suggest the Attach/Author/Shepherd/Approved-By lines move below that. And then "Posted Reports", "Action Items", and comments below that data.

Then toss the Info menu and its related handling.

The clear drawback to this design is for portrait-mode display. The Info is no longer accessible at the top of the page, but the window must be scrolled-down to see it. (tho the links remain easily visible/useful) ... Personally, I wouldn't mind the four info lines perma-displayed at the top of the left column, with the report below that.

**Comment by gstein** [comment]
The info display (on the left, above the actual report) could also take a signal from the actual agenda:

"Attachment $$, by $$, shepherded by $$"

or "Attachment $$ [$$ / $$]", but since the project name isn't needed on the line (like in the agenda) and no 80-col limit is applied ... this super-squeezed format doesn't seem as nice.

That just leaves the "Approved-by" to live somewhere.

**Comment by rubys** [comment]
I'd like to be able to optimize for both landscape and portrait.

For wide enough displays, this content could be at the top of the second column, and scroll with the data.

For narrow displays, the current implementation (available at all times as an overlay, but only when you request it) might be better.

**Comment by gstein** [comment]
I think moving the links, and adding two lines at the top/left would work for both orientations.

**Comment by rubys** [comment]
Showing how adapting to screen size could work:

https://github.com/apache/whimsy/commit/8ff058cc15cd1413092e258c6e1a9277545908c7
https://github.com/apache/whimsy/commit/1eab2b09f4bbf0ed6c57d7db1971bd0c5cdba68f

**Comment by sebbASF** [comment]
I assume this has been implemented.

If not, please raise a WHIMSY JIRA
