### ISSUE TITLE
Board traffic stats is broken for me.

### ISSUE THREAD

**Issue by tdunning** [apache/whimsy#71]
I went to https://whimsy.apache.org/officers/list-traffic.cgi and got a lurid yellow error message that said:
`
#<TypeError: no implicit conversion of Symbol into Integer>
  /x1/srv/whimsy/tools/mboxhdr2csv.rb:85:in `[]'
  /x1/srv/whimsy/tools/mboxhdr2csv.rb:85:in `find_who_from'
  /x1/srv/whimsy/www/officers/list-traffic.cgi:53:in `block in get_mails_month'
  /x1/srv/whimsy/www/officers/list-traffic.cgi:47:in `each'
  /x1/srv/whimsy/www/officers/list-traffic.cgi:47:in `get_mails_month'
  /x1/srv/whimsy/www/officers/list-traffic.cgi:97:in `block in display_monthly'
  /x1/srv/whimsy/www/officers/list-traffic.cgi:96:in `each'
  /x1/srv/whimsy/www/officers/list-traffic.cgi:96:in `display_monthly'
  /x1/srv/whimsy/www/officers/list-traffic.cgi:211:in `block (3 levels) in <main>'
  /x1/srv/whimsy/lib/whimsy/asf/themes.rb:195:in `block (3 levels) in _whimsy_body'
  /x1/srv/whimsy/lib/whimsy/asf/themes.rb:179:in `block (2 levels) in _whimsy_body'
  /x1/srv/whimsy/lib/whimsy/asf/themes.rb:178:in `block in _whimsy_body'
  /x1/srv/whimsy/lib/whimsy/asf/themes.rb:135:in `_whimsy_body'
  /x1/srv/whimsy/www/officers/list-traffic.cgi:182:in `block (2 levels) in <main>'
  /x1/srv/whimsy/www/officers/list-traffic.cgi:181:in `block in <main>'
`
I have no idea how this happened or how to fix it. It is not very important to me, either.

**Comment by sebbASF** [comment]
On Sun, 21 Jul 2019 at 22:47, Ted Dunning <notifications@github.com> wrote:

> I went to https://whimsy.apache.org/officers/list-traffic.cgi and got a
> lurid yellow error message that said:
> #<TypeError: no implicit conversion of Symbol into Integer>
> /x1/srv/whimsy/tools/mboxhdr2csv.rb:85:in[]'
> /x1/srv/whimsy/tools/mboxhdr2csv.rb:85:in find_who_from'
> /x1/srv/whimsy/www/officers/list-traffic.cgi:53:in block in
> get_mails_month'
> /x1/srv/whimsy/www/officers/list-traffic.cgi:47:in each'
> /x1/srv/whimsy/www/officers/list-traffic.cgi:47:in get_mails_month'
> /x1/srv/whimsy/www/officers/list-traffic.cgi:97:in block in
> display_monthly' /x1/srv/whimsy/www/officers/list-traffic.cgi:96:in each'
> /x1/srv/whimsy/www/officers/list-traffic.cgi:96:in display_monthly'
> /x1/srv/whimsy/www/officers/list-traffic.cgi:211:in block (3 levels) in
> '
> /x1/srv/whimsy/lib/whimsy/asf/themes.rb:195:in block (3 levels) in
> _whimsy_body' /x1/srv/whimsy/lib/whimsy/asf/themes.rb:179:in block (2
> levels) in _whimsy_body'
> /x1/srv/whimsy/lib/whimsy/asf/themes.rb:178:in block in _whimsy_body'
> /x1/srv/whimsy/lib/whimsy/asf/themes.rb:135:in _whimsy_body'
> /x1/srv/whimsy/www/officers/list-traffic.cgi:182:in block (2 levels) in
> <main>' /x1/srv/whimsy/www/officers/list-traffic.cgi:181:in block in '
> `
> I have no idea how this happened or how to fix it. It is not very
> important to me, either.


I get the same error.

Have looked at it briefly, but the bug is not immediately obvious to me.

**Comment by ShaneCurcuru** [comment]
"Lurid" yellow?  It's a nice simple #ff0 yellow... :grinning:
I don't recall code issues with this in the past, but I have occasionally had issues where malformed emails in some past archives got parsed but then provided bogus data to various utility functions.  Debugging should focus on the data, and figuring out how to scrub it sufficiently (even if lossy). Sorry, E_NO_FREE_TIME for another week or so.

**Comment by sebbASF** [comment]
I fixed one bug (passing value instead of hash), but this has not solved the issue.

The code uses both symbols and strings to index the hashes.
I'm not sure what the intention was here.
The data is cached in a JSON file; some of the keys are people's names which are not really ideal for symbolisation, so I suspect that strings should probably be used throughout.

**Comment by ShaneCurcuru** [comment]
If you make updates and choose a type, always defer to :symbols if possible.  I thought I had ensured it symbolized appropriately (mostly by trying to use Apache ID instead of other things) but may not have caught all cases.
