### ISSUE TITLE
Whimsy should check for project logos at a.o/logos/res/

### ISSUE THREAD

**Issue by Humbedooh** [apache/whimsy#76]
Instead of the old www.a.o/img/$pmc.jpg path, whimsy should preferably use www.a.o/logos/res/$pmc/default.png for checking for project logos. This is a more up to date location with more logos available.

**Comment by sebbASF** [comment]
Has this change been agreed with Central Services/M&P?

Are all the existing /img/ logos represented under /logos/res/?

If the change is agreed, there are various places on the www.apache.org website that need to be updated.

**Comment by sebbASF** [comment]
P.S. Please raise a WHIMSY JIRA instead of a GitHub issue in future
