### ISSUE TITLE
add link to roster/__self__

### ISSUE THREAD

**Issue by gstein** [apache/whimsy#92]
I think the main roster landing page (source at `www/roster/views/index.html.rb`) should have a prominent "your page" link at the top.

(I'm not quite sure how to edit that in)

**Comment by gstein** [comment]
Or, even on the very top-level whimsy page, where it lists types of Rosters, it could include "You"

**Comment by rlenferink** [comment]
> Or, even on the very top-level whimsy page, where it lists types of Rosters, it could include "You"

On the top level page it already displays `Your personal details` which links to \_\_self__. But adding it to the roster page may be useful as well.

**Comment by gstein** [comment]
Ah ha! Thanks!
